denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true
ts_schedule: false
mixed_precision: true
seed: 42
image_or_video_shape:
- 1
- 16
- 15
- 44
- 80
num_frame_per_block: 3
context_noise: 0
mode: templerun
causal: true
model_kwargs:
  timestep_shift: 5.0
  model_config: configs/distilled_model/templerun